version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    # platform: linux/x86_64 - descomentar se utilizar outra plataforma que não seja linux/x86_64
    working_dir: /app_front-end
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_back-end
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app_back-end
    # platform: linux/x86_64 - descomentar se utilizar outra plataforma que não seja linux/x86_64
    working_dir: /app_back-end
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://db:27017/beon
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mongo:5.0.7
    container_name: db_mongo
    # platform: linux/x86_64 - descomentar se utilizar outra plataforma que não seja linux/x86_64
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-data:/data/db
    restart: 'always'
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  redis-cache:
    image: redis
    container_name: redis
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis-cache:6379
    volumes:
      - ./db/redis-data:/data

networks:
  default:
    name: beon
    driver: bridge
