version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    # platform: linux/x86_64 - descomentar se utilizar outra plataforma que não seja linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    # platform: linux/x86_64 - descomentar se utilizar outra plataforma que não seja linux/x86_64
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=27017
      - MONGO_URI=mongodb://mongodb:27017/Beon
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mongo:5.0.7
    container_name: db
    # platform: linux/x86_64 - descomentar se utilizar outra plataforma que não seja linux/x86_64
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mongoadmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
